# ===== INDIVIDUALS POINTS ======
POINTS_PER_GOAL = 2
POINTS_PER_YELLOW_CARD = -2
POINTS_PER_RED_CARD = -3

# ===== TEAM POINTS ======
POINTS_PER_VICTORY = 2
POINTS_PER_DRAW = 1
POINTS_PER_DEFEAT = 0
POINTS_PER_MISSING_GAME = -2

# ===== GOALKEEPER POINTS ======
POINTS_PER_CLEANSHEET = 5
POINTS_PER_CONCEDED_GOALS = -0.5
