BUDGET = 200

POINTS_PER_GOAL = 2
POINTS_PER_VICTORY = 2
POINTS_PER_DEFEAT = -2
POINTS_PER_CLEANSHEET = 5

POINTS_PER_YELLOW_CARD = -1
POINTS_PER_RED_CARD = -2

POINTS_BEST_PLAYER = 5
POINTS_GOLEADOR = 5
